// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package fynex

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

// Use as canvas.NewImageFromResource(iconRedResource)
//
//go:embed assets/led_label_red.png
var iconRedData []byte
var iconRedResource = &fyne.StaticResource{
	StaticName:    "assets/led_label_red.png",
	StaticContent: iconRedData,
}

//go:embed assets/led_label_yellow.png
var iconYellowData []byte
var iconYellowResource = &fyne.StaticResource{
	StaticName:    "assets/led_label_yellow.png",
	StaticContent: iconYellowData,
}

//go:embed assets/led_label_green.png
var iconGreenData []byte
var iconGreenResource = &fyne.StaticResource{
	StaticName:    "assets/led_label_green.png",
	StaticContent: iconGreenData,
}
