// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package fynex

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/widget_background_lotr.png
var defaultBackgroundData []byte
var DefaultBackground = &fyne.StaticResource{
	StaticName:    "assets/widget_background_lotr.png",
	StaticContent: defaultBackgroundData,
}

//go:embed assets/widget_background_gradient1.png
var gradientBackgroundData []byte
var GradientBackground = &fyne.StaticResource{
	StaticName:    "assets/widget_background_gradient1.png",
	StaticContent: gradientBackgroundData,
}

//go:embed assets/lotr_icon.png
var developerIconData []byte
var DeveloperIcon = &fyne.StaticResource{
	StaticName:    "assets/lotr_icon.png",
	StaticContent: developerIconData,
}
